# Generated by Django 5.0.3 on 2024-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageName", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default="static/images/img1.jpeg", upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompVisionU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ManyToManyField(to="unityapp.image")),
            ],
        ),
    ]
